### ISSUE TITLE
Dependencies page missing

### ISSUE THREAD

**Issue by moraxy** [runnerty/docs.runnerty.io#8]
The text for the `Dependencies` page is missing, it was replaced with the one from `Executors` in 4b6c1e4ed21fa2d9f2a209e026a48703c93845d8 ([here](https://github.com/runnerty/docs.runnerty.io/commit/4b6c1e4ed21fa2d9f2a209e026a48703c93845d8#diff-93de759aea6ff6449f001ebbdbc4b2ac))

**Comment by alo** [comment]
Thanks @moraxy. New doc page is here! 
https://docs.runnerty.io/dependencies
